# Generated by Django 3.0.7 on 2020-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdb',
            name='catalogName',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
