# Generated by Django 3.0.7 on 2020-07-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20200701_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
