# Generated by Django 3.0.7 on 2020-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdb',
            name='catalogChoice',
            field=models.CharField(choices=[('code', 'Code'), ('stock', 'Stock'), ('news', 'News'), ('shoping', 'Shoping'), ('books', 'Books'), ('sport', 'Sport'), ('games', 'Games'), ('videos', 'Videos'), ('music', 'Music'), ('work', 'Work')], default='code', max_length=20),
        ),
    ]
