# Generated by Django 3.0.7 on 2020-07-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_linkdb_catalogchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdb',
            name='catalogName',
        ),
    ]
