# Generated by Django 3.0.7 on 2020-07-14 18:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_auto_20200714_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdb',
            name='catalogChoice',
            field=models.CharField(choices=[('code', 'Code'), ('news', 'News'), ('shopping', 'Shopping'), ('sport', 'Sport'), ('games', 'Games'), ('videos', 'Videos'), ('music', 'Music'), ('work', 'Work')], default='code', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='catalogChoice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('code', 'Code'), ('news', 'News'), ('shopping', 'Shopping'), ('sport', 'Sport'), ('games', 'Games'), ('videos', 'Videos'), ('music', 'Music'), ('work', 'Work')], default='code', max_length=48),
        ),
    ]
