# Generated by Django 3.0.7 on 2020-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_auto_20200714_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
