# Generated by Django 3.0.7 on 2020-07-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0013_auto_20200715_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdb',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.Profile'),
        ),
    ]
